# Config file

# Path to the input directory
INPUT_FOLDER: "/commons/Themas/Thema07/metagenomics/bioplastic/soil_metagenomics_16S/ariana_desiree/20240423_1108_MN35459_FAY08769_85e26567/fastq_pass"

# Path to the output directory
RESULTS: "/students/2024-2025/Thema07/metagenomics/bioplastic"


# Path to the minionqc 
MINIONQC_PATH: "/homes/machristo/metagenomics/metagenomics/workflow/scripts"

SAMPLE: ["combined_wgs_barcode01_report", "combined_wgs_barcode02_report", "combined_wgs_barcode03_report", "combined_wgs_barcode04_report", "combined_wgs_barcode05_report", "combined_wgs_barcode06_report"]
